[WIP] - Load pseudo data
frederikja163/CO2 pull request #5
Opened 2021-11-19 09:21 UTC by Emilorzz

2021-11-25 07:57 UTC, Aavild approved these changes

2021-11-25 08:12 UTC, frederikja163 approved these changes
The actual code looks good. Mostly some pointers on the coding style.

I think you might have misunderstood your task though. If I understood @Aavild correctly the actual task was to create two seperate functions. One for loading a file into memory, the other for writing a string from memory to a file.

I.E these two function prototypes
`void write_file(const char *fileName, const char *fileContents);`
`char* read_file(const char *fileName);`
The second function mallocs a string and outputs said string afterwards.

2021-11-25 08:12 UTC, frederikja163 commented on src/shared/loadPseudoData.c
> +int loadData(const char *input_file, const char *output_file) {
We use snake case for function names and lower camel case for parameters #3
`loadData` -> `load_data`
`input_file` -> `inputFile`
`output_file` -> `outputFile`

This function also has an int return value. But it never actually returns an int??

2021-11-25 08:12 UTC, frederikja163 commented on src/shared/loadPseudoData.h
> +int loadData(const char *input_file, const char *output_file);
Remember to update these names aswell

2021-11-25 08:12 UTC, frederikja163 commented on src/shared/loadPseudoData.c
> +        printf("Error : Unable to open %s for reading\n", input_file);
Please write to *stderr* when you have an error so its more visible in the console.
[how to print to stderr](https://stackoverflow.com/questions/39002052/how-i-can-print-to-stderr-in-c)

2021-11-25 08:12 UTC, frederikja163 commented on src/shared/loadPseudoData.c
> +        printf("Error : Unable to open %s for reading\n", output_file);
Please write to *stderr* when you have an error so its more visible in the console.
[how to print to stderr](https://stackoverflow.com/questions/39002052/how-i-can-print-to-stderr-in-c)

2021-11-25 08:12 UTC, frederikja163 commented on src/shared/loadPseudoData.c
> +    FILE *ifp, *ofp;
Could use better variable names here. What does ifp and ofp mean? etc.

2021-11-25 08:12 UTC, frederikja163 commented on src/shared/loadPseudoData.c
> +void copyData(FILE *ifp, FILE *ofp) {
We use snake case for function names and lower camel case for parameters #3
`copyData` -> `copy_data`

Also better with longer and more descriptive names.
Maybe consider if this should actually be a public function. We might just want this as a [static function](https://www.tutorialspoint.com/static-functions-in-c#:~:text=A%20static%20function%20in%20C,keyword%20before%20the%20function%20name.) within this .c file. For static functions it is also good to start the name with an `_` so the name becomes `_copy_data`

2021-11-25 08:12 UTC, frederikja163 commented on src/shared/loadPseudoData.c
> +        fputc(c, ofp);
Is there really no way of copying one line at aa time instead of only one character. Seems like this might be a bit heavy...

2021-11-25 08:13 UTC, frederikja163 requested changes
Woops, meant to request changes, my bad

2021-11-25 08:16 UTC, Emilorzz commented on src/shared/input.txt
> +regardless of wether said
the typo should be fixed

2021-11-26 09:14 UTC, frederikja163 approved these changes
Nice one! Tests will come soon.

2021-11-26 09:14 UTC, Aavild approved these changes

2021-11-26 09:14 UTC, Emilorzz commented on src/program/program.c
> +    char *input = "src/shared/input.txt";
main function is cleaned up

2021-11-26 09:15 UTC, merged