Calculating emissions
frederikja163/CO2 pull request #6
Opened 2021-11-19 10:04 UTC by AleksanderRDL

Merge? no? yes?

2021-12-02 14:03 UTC, Emilorzz commented on src/shared/calculateOptimalTime.h
> +#ifndef calculateOptimalTime_H
your define should be all caps

2021-12-02 14:09 UTC, AleksanderRDL commented on src/shared/calculateOptimalTime.h
> +#ifndef calculateOptimalTime_H
True

2021-12-02 14:22 UTC, Emilorzz approved these changes

2021-12-02 14:28 UTC, Emilorzz commented on src/shared/calculateOptimalTime.c
> +#include "loadPseudoData.h"
oh woops, change `loadPseudoData.h` to `fileIO.h`

2021-12-03 08:27 UTC, Aavild approved these changes

2021-12-03 10:40 UTC, Emilorzz approved these changes

2021-12-03 11:38 UTC, frederikja163 requested changes
Some changes have been requested over discord

2021-12-06 10:20 UTC, frederikja163 approved these changes
Looks good, could have more comments and more thorough testing, but its fine for now.

2021-12-06 10:27 UTC, Emilorzz approved these changes

2021-12-06 10:29 UTC, merged